### ISSUE TITLE
메인 페이지에서 프로필 페이지로 이동 (4h)

### ISSUE THREAD

**Issue by kukucorn** [boostcampwm-2021/web28-NaBaaang#9]
## Description

- [ ] 프로필 버튼을 클릭하면 프로필 페이지로 이동(2h)

## Constraints

- [ ] 로그인 되어 있지 않으면 로그인 페이지로 이동(2h)

**Comment by newgardener** [comment]
프로필 페이지를 만들지 않기로 결정
